name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: |
        # Basic static site validation (no build needed)
        if [ ! -f "index.html" ]; then
          echo "Missing index.html"
          exit 1
        fi
        echo "Static site validated"
